# -*- coding: utf-8 -*-
"""
TITLE:      readPhotometryCSV
DATE:       02-25-2022
AUTHOR:     MA540 Team 4
    
DESCRIPTION:
Read and plot photometry from a CSV file generated by blenderRenderRotation.py

"""

#%% IMPORTS %%#
import matplotlib.pyplot as plt
import numpy as np
import csv

#%% USER INPUTS %%#
filename = '2U-NOWINGS-V1_202202251510150000.csv';
path     = './photometry/';

#%% EXTRACT DATA %%#

# Load File
filepath = path + filename;
phot_file = open(filepath);
csvreader = csv.reader(phot_file);

# Parse CSV File
i = 0;
j = 0;
for row in csvreader:
    # Skip Text Lines
    if i == 0 or i == 2 or i == 4:
        i+=1;
        continue;
    
    # Header Line 1
    if i == 1:
        # Read Data
        file_id    = row[0];            # File ID for saving
        fps        = float(row[1]);     # Animation FPS
        dur        = float(row[2]);     # Animation Duration
        num_frames = int(row[3]);       # Number of frames
        sun_angle  = float(row[4]);     # Sun Direction (radians)
        
        # Initialize Vectors
        phot = np.zeros(num_frames);    # Normalized Photometry Data
        t    = np.zeros(num_frames);    # Time [s]
        i+=1;
        continue;
    
    # Header Line 2
    if i == 3:
        omega    = row[0];              # Angular Velocity [s^-1]
        x_rot    = row[1];              # Rotation Axis X
        y_rot    = row[2];              # Rotation Axis Y
        z_rot    = row[3];              # Rotation Axis Z
        sat_name = row[4];              # Satellite Type
        i+=1;
        continue;
    
    # Phot Data
    phot[j] = float(row[0]); 
    t[j]    = float(row[1]);
    j+=1;

phot_file.close();

#%% PLOT AND PROCESS %%#
plt.plot(t,phot,'.-');
plt.xlabel('Time [s]');
plt.ylabel('Magnitude');
plt.title('Satellite Photometry : ' + sat_name);